<a href="https://colab.research.google.com/github/plthiyagu/Personnel/blob/master/TF_IDF_and_Count_Vectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [13]:
sentence = ['I have a credit card account','My account card , debit card is lost','My credit card stopped working']

In [14]:
vectorizer = CountVectorizer()

In [15]:
countvec= vectorizer.fit_transform(sentence)

In [16]:
countvec.A

array([[1, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [1, 2, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1, 1]])

In [17]:
vectorizer.get_feature_names()

['account',
 'card',
 'credit',
 'debit',
 'have',
 'is',
 'lost',
 'my',
 'stopped',
 'working']

In [22]:
vectorizer = CountVectorizer(max_features=4)
countvec=vectorizer.fit_transform(sentence)

In [23]:
print(countvec.A)
print(vectorizer.get_feature_names())

[[1 1 1 0]
 [1 2 0 1]
 [0 1 1 1]]
['account', 'card', 'credit', 'my']


In [24]:
vectorizer = CountVectorizer(max_features=4,stop_words='english')
countvec=vectorizer.fit_transform(sentence)

In [25]:
print(countvec.A)
print(vectorizer.get_feature_names())

[[1 1 1 0]
 [1 2 0 1]
 [0 1 1 0]]
['account', 'card', 'credit', 'debit']


In [26]:
vectorizer = CountVectorizer(max_features=6,ngram_range=(1,2))
countvec=vectorizer.fit_transform(sentence)

In [27]:
print(countvec.A)
print(vectorizer.get_feature_names())

[[1 1 1 1 0 0]
 [1 2 0 0 1 0]
 [0 1 1 1 1 1]]
['account', 'card', 'credit', 'credit card', 'my', 'stopped']


TF= (#occurences of term t in document)/(#of words in documnet)

In [28]:
vectorizer = TfidfVectorizer(use_idf=False,norm='l1')
tfvec= vectorizer.fit_transform(sentence)

In [29]:
print(tfvec.A)
print(vectorizer.get_feature_names())

[[0.25       0.25       0.25       0.         0.25       0.
  0.         0.         0.         0.        ]
 [0.14285714 0.28571429 0.         0.14285714 0.         0.14285714
  0.14285714 0.14285714 0.         0.        ]
 [0.         0.2        0.2        0.         0.         0.
  0.         0.2        0.2        0.2       ]]
['account', 'card', 'credit', 'debit', 'have', 'is', 'lost', 'my', 'stopped', 'working']


In [30]:
vectorizer = TfidfVectorizer(use_idf=False,norm='l2')
tfvec= vectorizer.fit_transform(sentence)

In [31]:
print(tfvec.A)
print(vectorizer.get_feature_names())

[[0.5        0.5        0.5        0.         0.5        0.
  0.         0.         0.         0.        ]
 [0.33333333 0.66666667 0.         0.33333333 0.         0.33333333
  0.33333333 0.33333333 0.         0.        ]
 [0.         0.4472136  0.4472136  0.         0.         0.
  0.         0.4472136  0.4472136  0.4472136 ]]
['account', 'card', 'credit', 'debit', 'have', 'is', 'lost', 'my', 'stopped', 'working']


In [32]:
print(1/np.sqrt(4))

0.5


In [33]:
vectorizer = TfidfVectorizer(use_idf=False,norm=False)
tfvec= vectorizer.fit_transform(sentence)

In [34]:
print(tfvec.A)
print(vectorizer.get_feature_names())

[[1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 2. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 1. 1.]]
['account', 'card', 'credit', 'debit', 'have', 'is', 'lost', 'my', 'stopped', 'working']


IDF =log(# of documents/# documents with term t in it)

In [39]:
vectorizer_idf = TfidfVectorizer(smooth_idf=False)
tfidfvec= vectorizer_idf.fit_transform(sentence)

In [42]:
print(vectorizer_idf.idf_)
print(vectorizer_idf.get_feature_names())

[1.40546511 1.         1.40546511 2.09861229 2.09861229 2.09861229
 2.09861229 1.40546511 2.09861229 2.09861229]
['account', 'card', 'credit', 'debit', 'have', 'is', 'lost', 'my', 'stopped', 'working']


In [41]:
print(np.log(3/2)+1)

1.4054651081081644


In [43]:
tfidfvec.A

array([[0.45951737, 0.3269504 , 0.45951737, 0.        , 0.68614212,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.3055129 , 0.43474989, 0.        , 0.45618573, 0.        ,
        0.45618573, 0.45618573, 0.3055129 , 0.        , 0.        ],
       [0.        , 0.26959162, 0.37890161, 0.        , 0.        ,
        0.        , 0.        , 0.37890161, 0.56576828, 0.56576828]])