<a href="https://colab.research.google.com/github/plthiyagu/Personnel/blob/master/PADHAI_numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
!head cric_data-200320-181217.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


In [ ]:
cric_data=np.loadtxt("cric_data-200320-181217.tsv",skiprows=1)

In [ ]:
cric_data.shape

(225, 4)

In [ ]:
cric_data= cric_data[:,[1,2,3]]

In [ ]:
cric_data.shape

(225, 3)

In [ ]:
sachin_data= cric_data[:,0]

In [ ]:
rahul_data=cric_data[:,1]

In [ ]:
india_data= cric_data[:,2]

In [ ]:
def stats(col):
  print("Mean",np.mean(col))
  print("Median",np.median(col))
  print("IQR",np.percentile(col,75)-np.percentile(col,25))


In [ ]:
stats(sachin_data)

Mean 39.87555555555556
Median 27.0
IQR 57.0


In [ ]:
stats(rahul_data)

Mean 32.062222222222225
Median 22.0
IQR 46.0


In [ ]:
stats(india_data)

Mean 220.79555555555555
Median 216.0
IQR 98.0


In [ ]:
np.mean(cric_data,axis=0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [ ]:
np.median(cric_data,axis=0)

array([ 27.,  22., 216.])

In [ ]:
np.percentile(cric_data,75,axis=0)- np.percentile(cric_data,25,axis=0)

array([57., 46., 98.])

In [ ]:
np.histogram(sachin_data)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [ ]:
sachin_data.shape

(225,)

In [ ]:
sachin_data.reshape(9,25).shape

(9, 25)

In [ ]:
sachins_by_25s= sachin_data.reshape(9,25)

In [ ]:
np.mean(sachins_by_25s,axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [ ]:
np.mean(sachin_data[sachin_data >=100])

125.0

In [ ]:
np.mean(sachin_data[rahul_data <=10])

40.2112676056338

In [ ]:
qrs=np.percentile(india_data,[25,50,75,100])

In [ ]:
india_data <qrs

ValueError: ignored

In [ ]:
qrs= qrs.reshape(4,1)

In [ ]:
indices= india_data < qrs

In [ ]:
indices.shape

(4, 225)

In [ ]:
sachin_data[indices[0,:]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [ ]:
for i in range(4):
  print(i, np.mean(sachin_data[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


In [ ]:
snr = cric_data[:,0:2]

In [ ]:
np.argmax([1,2,5,4,1])

2

In [ ]:
is_rahul_higher=np.argmax(snr,axis=1)

In [ ]:
np.sum(is_rahul_higher)/225

0.4711111111111111

In [ ]:
np.where(is_rahul_higher==0,'Sachin','Rahul')

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

In [ ]:
x_arr= np.arange(0,101,5)

In [ ]:
sachin_data < x_arr

ValueError: ignored

In [ ]:
x_arr= x_arr.reshape(x_arr.shape[0],1)

In [ ]:
indices=sachin_data >= x_arr

In [ ]:
indices.shape

(21, 225)

In [ ]:
sachin_data[indices[1,:]]

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         7.,  37.,  14.,  21.,  62., 138.,  38.,  46.,  65.,  39.,  48.,
       141.,  62.,  12.,  41.,  11., 186.,  11.,  27.,  27.,  51.,  18.,
        32., 146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,  28.,
         6., 123., 120.,   7.,  81.,  54., 122.,  14., 100.,  15.,  57.,
        99.,  37.,  38.,  32.,  21.,  32.,  40.,   5.,   8.,   5.,  50.,
        30.,  37.,  89.,  98.,  83.,  93.,  52., 152.,   8.,  93.,  45.,
        26.,  16.,  47.,  89.,  53.,  16.,  81.,  14.,  78.,   6., 105.,
       122.,   9.,   8.,  28.,  35.,  69.,  13.,  97.,  93.,  36.,  39.,
        29.,  12.,  19.,  34., 100.,  44.,  82.,  79.,   6.,   9.,   8.,
        23.,  93.,  35.,  63.,  74.,   8., 117.,  39.,  49.,  64.,  43.,
        72.,   5.,  17.,  65.,  20., 141.,  28.,  44.,  27.,  60.,  68.,
       139.,  31.,  44.,  47.,   6.,  17.,  35.,  88., 114.,   7., 127.,
        45.,  33., 110., 146.,   7.,  25.,   9.,  1

In [ ]:
for i in range(x_arr.shape[0]):
  print(x_arr[i,0],np.mean(sachin_data[indices[i,:]])- x_arr[i,0])

0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558442
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306122
75 34.347826086956516
80 30.75
85 28.650000000000006
90 27.400000000000006
95 26.433333333333337
100 25.0


In [ ]:
sachin_cumscores=np.cumsum(sachin_data)

In [ ]:
np.histogram(sachin_cumscores, bins=np.arange(0,10000))

(array([0, 0, 0, ..., 0, 0, 0]),
 array([   0,    1,    2, ..., 9997, 9998, 9999]))

In [ ]:
import numpy as np
a= np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


In [ ]:
a=np.arange(10)
b= np.where(a%2 ==1, 1, a)
print(b)

[0 1 2 1 4 1 6 1 8 1]


In [ ]:
a= np.arange(3)
b= a.reshape(2,2)
print(b)

ValueError: ignored