<a href="https://colab.research.google.com/github/plthiyagu/Personnel/blob/master/PADHAI_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [54]:
N=100000000

In [55]:
%%time
list_= list(range(N))
for i in range(N):
  list_[i]= list_[i] * list_[i]

CPU times: user 23.9 s, sys: 3.24 s, total: 27.1 s
Wall time: 27.1 s


In [56]:
%%time
list_= list(range(N))
list_=[item * item for item in list_]

CPU times: user 9.49 s, sys: 8.42 s, total: 17.9 s
Wall time: 17.9 s


In [57]:
%%time
list_= list(range(N))
list_=map(lambda x:x *x,list_)

CPU times: user 2.59 s, sys: 1.51 s, total: 4.1 s
Wall time: 4.09 s


In [58]:
%%time
list_= list(range(N))
list_sum=0
for item in list_:
  list_sum += item

CPU times: user 13.1 s, sys: 1.76 s, total: 14.9 s
Wall time: 14.9 s


In [59]:
%%time
list_= list(range(N))
list_sum=sum(list_)


CPU times: user 3.16 s, sys: 1.55 s, total: 4.71 s
Wall time: 4.7 s


In [60]:
%%time
arr = np.arange(N)
arr= arr * arr

CPU times: user 414 ms, sys: 34.5 ms, total: 448 ms
Wall time: 450 ms


In [61]:
arr = np.arange(5)
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [62]:
arr= np.array([0,1,2,3,4])
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [63]:
arr.dtype

dtype('int64')

In [64]:
arr.ndim

1

In [65]:
arr.shape

(5,)

In [66]:
arr= np.array([0.0,1,2,3,4])
print(arr,type(arr))

[0. 1. 2. 3. 4.] <class 'numpy.ndarray'>


In [67]:
arr.dtype

dtype('float64')

In [68]:
arr.size

5

In [69]:
arr.itemsize

8

In [70]:
arr2d= np.array([[1,2,3],[4,5,6]])

In [71]:
arr2d.ndim

2

In [72]:
arr2d.shape

(2, 3)

In [73]:
arr2d.itemsize

8

In [74]:
arrd3d= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [75]:
arrd3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arrd3d.shape

(2, 2, 3)

In [77]:
arrd3d.ndim


3

In [78]:
arrd3d.size

12

In [79]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [81]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [82]:
np.random.randn(2,3)

array([[-1.30410285, -0.28686747,  0.37684026],
       [-1.76090064, -0.08347859,  1.38776803]])

In [83]:
np.random.rand(2,3)

array([[0.86445901, 0.54178898, 0.59263429],
       [0.67659145, 0.45634762, 0.48807816]])

In [84]:
np.random.randn(10,1)

array([[-0.39598079],
       [-1.35963692],
       [ 0.47604728],
       [ 1.23304525],
       [-1.60783157],
       [-0.19872805],
       [ 1.19221052],
       [-1.87484407],
       [ 1.67001407],
       [-0.47193614]])

In [85]:
np.random.randint(0,100,(2,3))

array([[ 5, 53, 40],
       [60, 65, 28]])

In [86]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [87]:
np.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [88]:
np.array([True,False,True,True])

array([ True, False,  True,  True])

In [89]:
str_arr=np.array(['1.4','2.1','1.1'])

In [90]:
str_arr

array(['1.4', '2.1', '1.1'], dtype='<U3')

In [91]:
arr=np.array(str_arr,dtype=float)

In [92]:
arr

array([1.4, 2.1, 1.1])

In [93]:
print(arrd3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [94]:
arrd3d[0,0,0]

1

In [95]:
arrd3d[1,0,2]

9

In [96]:
i=1
j=0
k=2
arrd3d[i,j,k]

9

In [97]:
arrd3d[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [98]:
arrd3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [99]:
arrd3d[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [100]:
arrd3d[arrd3d % 2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [101]:
arrd3d[(arrd3d % 2 ==0) & (arrd3d >4)]

array([ 6,  8, 10, 12])

In [102]:
arr_slice = arrd3d[:,:,0:2]

In [103]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [104]:
arr_slice.ndim

3

In [105]:
arr_slice.shape

(2, 2, 2)

In [106]:
arr_slice[0,0,1]

2

In [107]:
arr_slice[0,0,0] =1729

In [108]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [109]:
arrd3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [110]:
arr_slice[0,0,0] =1
arrd3d[0,0,0]=1

In [111]:
arr_slice = np.copy(arrd3d[:,:,0:2])

In [112]:
arr_slice[0,0,0] =1729

In [113]:
arr_slice


array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [114]:
arrd3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [115]:
arr= np.random.randint(0,10,(5))

In [116]:
arr

array([7, 0, 2, 5, 2])

In [117]:
my_indices=[1,3,4]

In [118]:
arr[my_indices]

array([0, 5, 2])

In [119]:
import numpy as np

arr1= np.random.randn(3,4)
arr2= np.random.randn(3,4)

In [120]:
arr1+arr2

array([[-1.35104143,  1.09057086,  2.4187344 ,  1.02913902],
       [-0.5608513 , -0.31042214, -2.04122951,  0.41758632],
       [ 0.68397646,  0.52392582, -2.13333918, -0.24907465]])

In [121]:
arr1 - arr2

array([[-2.04395271, -0.36811672, -0.5833401 , -1.72400854],
       [-1.63601728,  4.25400331,  0.42333309, -0.93219003],
       [ 1.40841868,  1.89898331, -0.3244912 ,  0.17400024]])

In [122]:
arr1 * arr2

array([[-0.58810743,  0.26345872,  1.3774976 , -0.47826958],
       [-0.59049959, -4.50004557,  0.99685175, -0.17364998],
       [-0.37895484, -0.83290984,  1.11146038,  0.00794052]])

In [123]:
arr1/ arr2

array([[-4.89960869,  0.49527681,  0.61137533, -0.25239094],
       [-2.04328321, -0.86398194,  0.65646392, -0.38125109],
       [-2.88828438, -1.76204206,  1.35878217,  0.17744945]])

In [124]:
np.exp(arr1)

array([[0.18314134, 1.43508929, 2.50351851, 0.70649811],
       [0.33339267, 7.18352773, 0.44532621, 0.7731348 ],
       [2.84680574, 3.35836607, 0.29260983, 0.96315858]])

In [125]:
np.log(np.exp(arr1))

array([[-1.69749707,  0.36122707,  0.91769715, -0.34743476],
       [-1.09843429,  1.97179059, -0.80894821, -0.25730185],
       [ 1.04619757,  1.21145457, -1.22891519, -0.0375372 ]])

In [126]:
np.sin(arr1)

array([[-0.99198419,  0.35342238,  0.7942044 , -0.34048696],
       [-0.89049607,  0.92067335, -0.72356157, -0.25447216],
       [ 0.86552498,  0.9361285 , -0.94212566, -0.03752839]])

In [127]:
np.cos(arr1)

array([[-0.12636202,  0.93546385,  0.6076507 ,  0.94024924],
       [ 0.45499094, -0.39033393,  0.69025985,  0.9670801 ],
       [ 0.50086576,  0.35165811,  0.33525995,  0.99929556]])

In [128]:
np.sqrt(arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan, 0.60102169, 0.95796511,        nan],
       [       nan, 1.40420461,        nan,        nan],
       [1.022838  , 1.10066097,        nan,        nan]])

In [129]:
arr_inv=1/arr1

In [130]:
arr_inv

array([[ -0.58910264,   2.76834181,   1.08968411,  -2.87823823],
       [ -0.91038673,   0.50715325,  -1.23617308,  -3.88648579],
       [  0.9558424 ,   0.82545398,  -0.8137258 , -26.64023694]])

In [131]:
arr1=np.zeros((3,5))

In [132]:
arr_inv= 1/arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [133]:
arr_inv

array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [134]:
np.isinf(arr_inv[0,0])

True

In [135]:
ndim=2

In [143]:
npoints=1000000

In [144]:
points= np.random.rand(npoints,ndim)

In [145]:
points[0:2,:]

array([[0.85452999, 0.81841073],
       [0.34432574, 0.62577559]])

In [146]:
dfo= np.zeros((npoints,1))
outside_points=0

In [147]:
%%time
for i in range(npoints):
  for j in range(ndim):
    dfo[i] += points[i,j] ** 2
    dfo[i]=np.sqrt(dfo[i])
    if dfo[i] >1:
      outside_points += 1


CPU times: user 14 s, sys: 44.2 ms, total: 14 s
Wall time: 14 s


In [148]:
print("Fraction of the points outside is",outside_points/npoints)

Fraction of the points outside is 0.33355


In [149]:
%%time
sq_points= points * points
dfo = np.sum(sq_points,axis=1)
outside_points = np.sum(dfo > 1)


CPU times: user 27 ms, sys: 0 ns, total: 27 ms
Wall time: 31 ms


In [151]:
print("Fraction of the points outside is",outside_points/npoints)

Fraction of the points outside is 0.214941


In [152]:
%%time
outside_points = np.sum(np.sqrt(np.sum(points * points,axis=1))>1)

CPU times: user 23.5 ms, sys: 12.1 ms, total: 35.6 ms
Wall time: 37.4 ms


In [153]:
print("Fraction of the points outside is",outside_points/npoints)

Fraction of the points outside is 0.214941


In [164]:
def area_outside_square(npoints, ndim):
  points = np.random.rand(npoints,ndim)
  return np.sum(np.sqrt(np.sum(points * points,axis=1))>1)/npoints


In [165]:
%%time
area_outside_square(100000,2)

CPU times: user 6.47 ms, sys: 0 ns, total: 6.47 ms
Wall time: 6.27 ms


0.21412

In [168]:
for i in range(2, 11):
  print(i, area_outside_square(100000,i))

2 0.21661
3 0.47445
4 0.69204
5 0.83416
6 0.92073
7 0.96301
8 0.98406
9 0.99325
10 0.99733


In [182]:
arr1= np.arange(6)

In [183]:
arr1.shape

(6,)

In [201]:
arr1= arr1.reshape((3,2))

In [202]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [198]:
arr2= np.arange(6).reshape((3,2))

In [199]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [203]:
arr1+arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [204]:
arr2[0].reshape((1,2))

array([[0, 1]])

In [205]:
arr1 +arr2[0].reshape((1,2))

array([[0, 2],
       [2, 4],
       [4, 6]])

In [207]:
arr2[:,0].reshape(3,1)

array([[0],
       [2],
       [4]])

In [208]:
arr1+arr2[:,0].reshape(3,1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [209]:
arr1 +1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [210]:
arr1= np.arange(24).reshape((2,3,4))

In [211]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [212]:
arr2= np.ones((1,4))

In [213]:
arr1+arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [214]:
arr1= np.arange(4)

In [216]:
arr2= np.arange(5)

In [217]:
print(arr1.shape,arr2.shape)

(4,) (5,)


In [218]:
arr1 +arr2

ValueError: ignored

In [220]:
arr1.reshape(4,1) + arr2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [233]:
planetsmalltext=np.loadtxt("planets_small-200320-181217.txt",skiprows=1,
                           usecols=(1,2,3,4,5,6,7,8,9))

In [234]:
planetsmalltext

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [235]:
planetsmalltext.shape

(3, 9)

In [236]:
planet=np.genfromtxt("planets-200320-181217.txt",skip_header=1,
                           usecols=[1,2,3,4,5,6,7,8,9])

In [237]:
planet



array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [238]:
planet.shape

(20, 9)

In [232]:
np.isnan(planet)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [240]:
planet_new= np.nan_to_num(planet, nan=-1)

In [241]:
planet_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [242]:
np.savetxt('planetsnew.txt',planet_new,delimiter=',')

In [243]:
np.save("planetsnew",planet_new)

In [250]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 2.9K Jul 26 19:55 cric_data-200320-181217.tsv
-rw-r--r-- 1 root root 1.7M Jul 26 23:23 many_arrs.npz
-rw-r--r-- 1 root root 1.5K Jul 26 19:55 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul 26 23:00 planetsnew.npy
-rw-r--r-- 1 root root 4.5K Jul 26 22:59 planetsnew.txt
-rw-r--r-- 1 root root  254 Jul 26 19:55 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jul 10 16:29 sample_data


In [3]:
arr1 = np.random.rand(1000,10)
arr2 = np.random.rand(2000,5)
arr3= np.random.rand(20,10000)

In [4]:
np.savez("many_arrs",arr1,arr2,arr3)

In [5]:
arrs= np.load("many_arrs.npz")

In [6]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [7]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [8]:
arrs['arr_0'].shape

(1000, 10)

In [9]:
np.savez_compressed("many_arrs",arr1,arr2,arr3)

In [10]:
!ls -lh

total 1.6M
-rw-r--r-- 1 root root 1.6M Jul 27 01:05 many_arrs.npz
drwxr-xr-x 1 root root 4.0K Jul 10 16:29 sample_data


In [11]:
arr1= np.zeros((10000,10000))

In [18]:
np.savez("zeros",arr1)

In [20]:
np.savez_compressed("zeros_compressed",arr1)

In [21]:
!ls -lh

total 766M
-rw-r--r-- 1 root root 1.6M Jul 27 01:05 many_arrs.npz
drwxr-xr-x 1 root root 4.0K Jul 10 16:29 sample_data
-rw-r--r-- 1 root root 760K Jul 27 01:09 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Jul 27 01:09 zeros.npz
