<a href="https://colab.research.google.com/github/plthiyagu/AI-Engineering/blob/master/02-Numpy/12_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrix = np.array([[45,34],[67,58]])
# Create a matrix
print("The original matrix is given by n", matrix)
# Check the dimension of the matrix
print("The dimension of the given matrix is", matrix.ndim)

The original matrix is given by n [[45 34]
 [67 58]]
The dimension of the given matrix is 2


Matrices Addition and Subtraction


In [2]:
matrix_1 = np.array([[45,34],[67,58]])
matrix_2 = np.array([[35,24],[57,48]])
# Add the two matrices
print("The result after adding matrix 1 and matrix 2 is given by n" , np.add(matrix_1, matrix_2))
# Subtract one matrix from the other matrices
print("The result after subtracting matrix 1 from matrix 2 is given by n" , np.subtract(matrix_1, matrix_2))
print("The result after subtracting matrix 2 from matrix 1 is given by n" , np.subtract(matrix_2, matrix_1))

The result after adding matrix 1 and matrix 2 is given by n [[ 80  58]
 [124 106]]
The result after subtracting matrix 1 from matrix 2 is given by n [[10 10]
 [10 10]]
The result after subtracting matrix 2 from matrix 1 is given by n [[-10 -10]
 [-10 -10]]


Shape and Size of a Matrix

In [3]:
matrix = np.array([[45,34,75],[67,58,89]])
# Finding number of rows and columns in the matrix
print("The number of rows and columns in the given matrix are " + str(matrix.shape[0]) + " and " + str(matrix.shape[1]) + " respectively")
# Number of elements in the matrix
print("The size of the given matrix is" , matrix.size)

The number of rows and columns in the given matrix are 2 and 3 respectively
The size of the given matrix is 6


Converting a given Dense matrix to a Sparse Matrix
Let’s first understand what exactly it means by Sparse and Dense Matrix.

A sparse matrix is a matrix that consists of mostly zero values. And Sparse matrices are different from matrices with mostly non-zero values, which are Known as dense matrices.

In [4]:
from scipy import sparse
# Create a Dense Matrix
dense_matrix = np.array([[0,0],[0,17],[78,0]])
# Convert Dense matrix to Sparse matrix
sparse_matrix = sparse.csr_matrix(dense_matrix)
print("The sparse matrix corresponding to a given dense matrix is given by n" , sparse_matrix)

The sparse matrix corresponding to a given dense matrix is given by n   (1, 1)	17
  (2, 0)	78


Matrix Transpose
In Matrix Transpose, we can convert a row vector to a column vector and vice versa i.e, row becomes columns and columns becomes rows.

If we have matrix A = [aij]mxn, then the transpose of this matrix is AT = [aji]n×m

In [5]:
import numpy as np
matrix = np.array([[45,34],[67,58]])
print("The original matrix is given by n" , matrix)
print("The transpose matrix of the given matrix is n" , matrix.T)

The original matrix is given by n [[45 34]
 [67 58]]
The transpose matrix of the given matrix is n [[45 67]
 [34 58]]


Mean, Variance, and Standard Deviation of a Matrix

In [6]:
import numpy as np
matrix = np.array([[45,34],[67,58], [23,89]])
# Finding the mean of a matrix elements
print("The mean of the elements of a matrix is equal to", np.mean(matrix))
# Finding the Variance of a matrix elements
print("The variance of the elements of a matrix is equal to", np.var(matrix))
# Finding the Standard Deviation of a matrix elements
print("The standard deviation of the elements of a matrix is equal to", np.std(matrix))
print("The standard deviation of the elements of a matrix is equal to", np.sqrt(np.var(matrix)))

The mean of the elements of a matrix is equal to 52.666666666666664
The variance of the elements of a matrix is equal to 473.5555555555555
The standard deviation of the elements of a matrix is equal to 21.761331658599286
The standard deviation of the elements of a matrix is equal to 21.761331658599286


Trace of a Matrix

In [7]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])
# Get the diagonal elements of a matrix
print("The diagonal elements of a given matrix are n", matrix.diagonal())
# Finding the trace of the matrix
print("The trace of a given matrix is equal to", matrix.diagonal().sum())

The diagonal elements of a given matrix are n [1 5 9]
The trace of a given matrix is equal to 15


Finding minimum and maximum elements from a Matrix

In [8]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6], [7,8,9]])
# Find the minimum element of the matrix
print("The minimum element in a given matrix is", np.min(matrix))
# Find the maximum element of the matrix
print("The maximum element in a given matrix is", np.max(matrix))

The minimum element in a given matrix is 1
The maximum element in a given matrix is 9


Determinant of a Matrix

In [9]:
import numpy as np
matrix = np.array([[1,2,4],[3,4,6], [7,8,5]])
# Find the determinant of the matrix
print("The determinant of the given matrix is equal to", np.linalg.det(matrix))

The determinant of the given matrix is equal to 9.999999999999993


Matrix Multiplication

In [10]:
import numpy as np
matrix_1 = np.array([[45,34],[67,58]])
matrix_2 = np.array([[35,24],[57,48]])
print("The matrix multiplication of given two matrices is given by n", np.matmul(matrix_1, matrix_2))

The matrix multiplication of given two matrices is given by n [[3513 2712]
 [5651 4392]]


Element wise operations using an inline function (Lambda)

In [11]:
import numpy as np
matrix = np.array([[1,2,4],[3,4,6], [7,8,5]])
addition = lambda i:i+5
add_5_vec = np.vectorize(addition)
print("The matrix after adding 5 to all its elements is n", add_5_vec(matrix))

The matrix after adding 5 to all its elements is n [[ 6  7  9]
 [ 8  9 11]
 [12 13 10]]


Inverse of a Matrix

In [12]:
import numpy as np
matrix = np.array([[1,2,4],[3,4,6], [7,8,5]])
# Finding the inverse of a matrix
print("The inverse matrix of a given matrix is n", np.linalg.inv(matrix))

The inverse matrix of a given matrix is n [[-2.8  2.2 -0.4]
 [ 2.7 -2.3  0.6]
 [-0.4  0.6 -0.2]]


Reshape a given Matrix

In [13]:
import numpy as np
matrix = np.array([[1,2,4],[3,4,6],[7,8,5],[9,2,1]])
print("The reshaped matrix is given by n", matrix.reshape(6,2))

The reshaped matrix is given by n [[1 2]
 [4 3]
 [4 6]
 [7 8]
 [5 9]
 [2 1]]
