<a href="https://colab.research.google.com/github/plthiyagu/Personnel/blob/master/Dot_product_of_two_sparse_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def sparse_dot_product(vec1, vec2):
  """
    input: vec1 and vec2 list of tuples
           representing sparse vectors

    outut: the dot product of the two vectors.
  """
  len1 = len(vec1)
  len2 = len(vec2)
  if (len1==0) or (len2==0):
    raise ValueError('One of the vectors is empty!')

  pointer1 = 0
  pointer2 = 0
  product = 0
  while(pointer1 < len1) and (pointer2 < len2):
    if vec1[pointer1][0] == vec2[pointer2][0]:
      product += (vec1[pointer1][1] * vec2[pointer2][1])
      pointer1 += 1
      pointer2 += 1
    elif vec1[pointer1][0] < vec2[pointer2][0]:
      pointer1 += 1
    elif vec2[pointer2][0] < vec1[pointer1][0]:
      pointer2 += 1
  return product



In [0]:
import numpy as np
from scipy.sparse import csc_matrix
a=csc_matrix((3, 4), dtype=np.int8).toarray()
b=csc_matrix((3, 4), dtype=np.int8).toarray()


In [8]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [16]:
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [20]:
# create dense matrix
from numpy import array
A = array([[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]])
A

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [21]:
c=sparse_dot_product(a,b)
c

0