<a href="https://colab.research.google.com/github/plthiyagu/Personnel/blob/master/Numpy_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Numpy Library
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image


In [2]:
list1=[10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
# Display the type of an object
type(list1)

list

In [4]:
#Convert list to Numpy Array
arr1= np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [7]:
# Display type of an object

type(arr1)

numpy.ndarray

In [6]:
#Memory address of an array object
arr1.data

In [8]:
#Datatype of array
arr1.dtype

dtype('int64')

In [9]:
# Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [14]:
#Shape of Array
arr3 = np.arange(0,10)
arr3.shape

(10,)

In [15]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Size of array
arr3.size

10

In [17]:
# Dimension 
arr3.ndim

1

In [18]:
# Datatype of object
arr3.dtype

dtype('int64')

In [19]:
# Bytes consumed by one element of an array object
arr3.itemsize

8

In [20]:
# Bytes consumed by an array object
arr3.nbytes

80

In [21]:
# Length of array
len(arr3)

10

In [22]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Generate an array of ones with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [25]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [26]:
# Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [27]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 ==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [30]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [31]:
# Create an array of random values
np.random.random(4)

array([0.43732224, 0.01603872, 0.52214319, 0.04572257])

In [32]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,5)

array([210, 198, 472, 295, 236])

In [33]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,10)

array([395, 490, 445, 263, 357,  74, 217, 168, 209, 413])

In [34]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [35]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [36]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [38]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [39]:
# Extract Integer part
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [40]:
# Truncate decimal part
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [41]:
# Convert Float Array to Integer array
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [42]:
# Normal distribution (mean=0 and variance=1)
b2 =np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [43]:
arr1

array([10, 20, 30, 40, 50, 60])

In [45]:
# Enumerate for Numpy Arrays
for index,value in np.ndenumerate(arr1):
  print(index,value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [46]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
# Sum of all elements in an array
arr2.sum()

190

In [48]:
# Cumulative Sum
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [49]:
# Find Minimum number in an array
arr2.min()

1

In [50]:
# Find MAX number in an array
arr2.max()

19

In [51]:
# Find INDEX of Minimum number in an array
arr2.argmin()

0

In [52]:
# Find INDEX of MAX number in an array
arr2.argmax()

18

In [53]:
# Find mean of all numbers in an array
arr2.mean()

10.0

In [54]:
# Find median of all numbers present in arr2
np.median(arr2)

10.0

In [55]:
# Variance
np.var(arr2)

30.0

In [56]:
# Standard deviation
np.std(arr2)

5.477225575051661

In [57]:
# Calculating percentiles
np.percentile(arr2,70)

13.6

In [58]:
# 10th & 70th percentile
np.percentile(arr2,[10,70])

array([ 2.8, 13.6])

In [59]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [60]:
# SUM of all numbers in a 2D array
A.sum()

129

In [61]:
# MAX number in a 2D array
A.max()

22

In [62]:
# Minimum
A.min()

0

In [63]:
# Column wise mimimum value 
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [64]:
# Row wise mimimum value 
np.amin(A, axis=1)

array([0, 5, 1, 3])

In [65]:
# Mean of all numbers in a 2D array
A.mean()

8.0625

In [66]:
# Mean
np.mean(A)

8.0625

In [67]:
# Median
np.median(A)

6.5

In [68]:
# 50 percentile = Median
np.percentile(A,50)

6.5

In [69]:
np.var(A)

40.30859375

In [70]:
np.std(A)

6.348904925260734

In [71]:
np.percentile(arr2,70)

13.6

In [72]:
# Enumerate for Numpy 2D Arrays
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [73]:
a = np.array([7,5,3,9,0,2])

In [74]:
# Access first element of the array
a[0]

7

In [75]:
# Access all elements of Array except first one.
a[1:]

array([5, 3, 9, 0, 2])

In [76]:
# Fetch 2nd , 3rd & 4th value from the Array
a[1:4]

array([5, 3, 9])

In [77]:
# Get last element of the array
a[-1]

2

In [78]:
a[-3]

9

In [79]:
a[-6]

7

In [80]:
a[-3:-1]

array([9, 0])

In [81]:
ar = np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [82]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar % 2 == 0, 0 , ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [83]:
ar2 = np.array([10, 20 , 30 , 10 ,10 ,20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [84]:
# Replace 10 with value 99
rep2 = np.where(ar2 == 10, 99 , ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [85]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
# Replace values at INDEX loc 0,3,5 with 33,55,99
np.put(p2, [0, 3 , 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [87]:
a = np.array([10 ,np.nan,20,30,60,np.nan,90,np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [88]:
# Search for missing values and return as a boolean array
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [89]:
# Index of missing values in an array
np.where(np.isnan(a))

(array([1, 5]),)

In [90]:
# Replace all missing values with 99
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [91]:
# Check if array has any NULL value
np.isnan(a).any()

False

In [92]:
A = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [93]:
# Search for missing values and return as a boolean array
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [94]:
# Index of missing values in an array
np.where(np.isnan(A))

(array([0, 1, 2]), array([2, 0, 1]))

In [95]:
a = np.zeros(20).reshape(2,-1)
b = np.repeat(1, 20).reshape(2,-1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [96]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [97]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
a1 = np.array([[1], [2], [3]])
b1 = np.array([[4], [5], [6]])

In [99]:
a1

array([[1],
       [2],
       [3]])

In [100]:
b1

array([[4],
       [5],
       [6]])

In [102]:
np.vstack([a1,b1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [103]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [104]:
np.hstack([a1,b1])


array([[1, 4],
       [2, 5],
       [3, 6]])

In [105]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [106]:
np.intersect1d(c1,c2)

array([20, 40, 60])

In [107]:
# Remove common elements of C1 & C2 array from C1

np.setdiff1d(c1,c2)

array([10, 30, 50])

In [108]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

np.where(a == b) # returns the indices of elements in an input array where the given condition is satisfied.

(array([1, 4]),)

In [109]:
# Return an array where condition is satisfied
a[np.where(a == b)]

array([2, 8])

In [110]:
# Return all numbers betweeen 20 & 35
a1 = np.arange(0,60)
a1[np.where ((a1>20) & (a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [113]:
# Return all numbers betweeen 20 & 35 OR numbers divisible by 10
a1=np.arange(0,60)
a1[np.where(((a1>20) & (a1<35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [114]:
# Return all numbers betweeen 20 & 35 using np.logical_and
a1[np.where(np.logical_and(a1>20, a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [115]:
a = np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [116]:
# Check whether number 11 & 20 are present in an array
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [117]:
#Display the matching numbers
a[np.isin(a,20)]

array([20])

In [118]:
# Check whether number 33 is present in an array
np.isin(a, 33)

array([False, False, False, False, False, False, False])

In [119]:
a[np.isin(a, 33)]

array([], dtype=int64)

In [120]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b

array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [121]:
# Check whether number 10 & 70 are present in an array
np.isin(b, [10,70])

array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [122]:
# Display the indices where match occurred
np.where(np.isin(b, [10,70]))

(array([0, 4, 5, 6, 8]),)

In [123]:
# Display the matching values
b[np.where(np.isin(b, [10,70]))]

array([10, 10, 10, 70, 70])

In [124]:
# Display the matching values
b[np.isin(b, [10,70])]

array([10, 10, 10, 70, 70])

In [125]:
a4 = np.arange(10,30)

In [126]:
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [127]:
# Reverse the array
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [128]:
# Reverse the array
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [129]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [130]:
# Reverse ROW positions
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [131]:
# Reverse COLUMN positions
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [132]:
# Reverse both ROW & COLUMN positions
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

In [133]:
a = np.array([10,5,2,22,12,92,17,33])

In [134]:
# Sort array in ascending order
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [135]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [136]:
# Sort along rows
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [137]:
# Sort along rows
np.sort(a3,axis =1)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [138]:
# Sort along columns
np.sort(a3,axis =0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [139]:
# Sort in descending order
b = np.sort(a)
b = b[::-1]
b

array([92, 33, 22, 17, 12, 10,  5,  2])

In [140]:
# Sort in descending order
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

In [141]:
# Sort in descending order
a[::-1].sort()
a

array([92, 33, 22, 17, 12, 10,  5,  2])

In [142]:
p = np.arange(0,50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [143]:
np.random.shuffle(p)
p

array([27, 26, 35, 41, 45, 43,  6,  4, 34, 16,  3,  1, 31, 25, 48, 40, 21,
        2, 13, 47,  5, 37, 14, 23, 32, 22,  8, 20, 44, 28, 36, 10, 30, 19,
       24, 29, 33, 42, 11, 17, 12,  0, 15, 49,  7, 18,  9, 46, 38, 39])

In [145]:
np.random.shuffle(p)
p

array([19, 36,  3, 44, 38, 35, 47, 16, 27, 31, 34, 21, 10, 22, 26, 12, 48,
        0, 39, 33,  7, 46, 43, 20,  5, 18, 49,  1, 15,  2, 30,  8, 37, 14,
       28, 11, 25, 13, 41, 24, 40, 29, 23, 45,  9,  4, 42, 17, 32,  6])

In [147]:
# Return "n" largest numbers in an Array
n = 4
p[np.argsort(p)[-n:]]

array([46, 47, 48, 49])

In [148]:
# Return "n" largest numbers in an Array
p[np.argpartition(-p,n)[:n]]

array([47, 46, 49, 48])

In [149]:
# Return "n" smallest numbers in an Array
p[np.argsort(-p)[-n:]]

array([3, 2, 1, 0])

In [150]:
# Return "n" smallest numbers in an Array
p[np.argpartition(p,n)[:n]]

array([0, 1, 2, 3])

In [151]:
a5 = [10,20,30] 
a5

[10, 20, 30]

In [152]:
# Repeat whole array twice
np.tile(a5, 2)

array([10, 20, 30, 10, 20, 30])

In [153]:
# Repeat each element in an array thrice
np.repeat(a5, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [154]:
d1 = np.arange(0,10)
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
d2 = np.arange(0,10)
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
d3 = np.arange(10,20)
d3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [157]:
d4 = d1[::-1]
d4

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [158]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res1 = np.allclose(d1,d2)
res1

True

In [159]:
# Compare arrays using "allclose" function. If this function returns False then Arrays are not equal
res2 = np.allclose(d1,d3)
res2

False

In [160]:
# Compare arrays using "allclose" function.
res3 = np.allclose(d1,d4)
res3

False

In [161]:
# unique numbers in an array
b = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10])
np.unique(b)

array([10, 20, 30])

In [162]:
# unique numbers in an array along with the count E.g value 10 occurred maximum times (5 times) in an array "b"
val , count = np.unique(b,return_counts=True)
val,count

(array([10, 20, 30]), array([6, 3, 4]))

In [163]:
# 10 is the most frequent value 
np.bincount(b).argmax()

10

In [164]:
d5 = np.arange(10,100,10)
d5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [165]:
# Make arrays immutable  
d5.flags.writeable = False

In [166]:
d5[0]=99

ValueError: ignored

In [167]:
d5[2] = 11

ValueError: ignored

In [168]:
# Load data from a text file using loadtext
p4 = np.loadtxt('sample.txt', 
                dtype = np.integer # Decides the datatype of resulting array
               )
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [169]:
# Load data from a text file using genfromtxt
p5 = np.genfromtxt('sample0.txt',dtype='str')
p5

array([['Asif', 'India', 'Cricket'],
       ['John', 'USA', 'Hockey'],
       ['Ramiro', 'Canada', 'Football']], dtype='<U8')

In [170]:
# Accessing specific rows
p5[0]

array(['Asif', 'India', 'Cricket'], dtype='<U8')

In [171]:
p6 = np.genfromtxt('sample2.txt', 
                   delimiter=' ', 
                   dtype=None, 
                   names=('Name', 'ID', 'Age')
                  )
p6

array([(b'Name', b'ID', b'Age'), (b'Asif', b'22', b'29'),
       (b'John', b'45', b'33'), (b'Ramiro', b'55', b'67'),
       (b'Michael', b'67', b'55'), (b'Klaus', b'44', b'32'),
       (b'Sajad', b'23', b'53')],
      dtype=[('Name', 'S7'), ('ID', 'S2'), ('Age', 'S3')])

In [172]:
# Skip header using "skiprows" parameter
p6 = np.loadtxt('sample2.txt', 
                   delimiter=' ', 
                   dtype=[('Name', str, 50), ('ID', np.integer), ('Age', np.integer)], 
                   skiprows=1
                  )
p6

array([('Asif', 22, 29), ('John', 45, 33), ('Ramiro', 55, 67),
       ('Michael', 67, 55), ('Klaus', 44, 32), ('Sajad', 23, 53)],
      dtype=[('Name', '<U50'), ('ID', '<i8'), ('Age', '<i8')])

In [173]:
# Return only first & third column using "usecols" parameter
np.loadtxt('sample.txt', delimiter =' ', usecols =(0, 2))

array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

In [174]:
# Return only three rows using "max_rows" parameter
p6 = np.loadtxt('sample2.txt', 
                   delimiter=' ', 
                   dtype=[('Name', str, 50), ('ID', np.integer), ('Age', np.integer)], 
                   skiprows=1,
                   max_rows = 3
                  )
p6

array([('Asif', 22, 29), ('John', 45, 33), ('Ramiro', 55, 67)],
      dtype=[('Name', '<U50'), ('ID', '<i8'), ('Age', '<i8')])

In [175]:
# Skip header using "skip_header" parameter
p6 = np.genfromtxt('sample2.txt', 
                   delimiter=' ', 
                   dtype=[('Name', str, 50), ('ID', np.integer), ('Age', np.float)], 
                   names=('Name', 'ID', 'Age'),
                   skip_header=1
                  )
p6

array([('Asif', 22, 29.), ('John', 45, 33.), ('Ramiro', 55, 67.),
       ('Michael', 67, 55.), ('Klaus', 44, 32.), ('Sajad', 23, 53.)],
      dtype=[('Name', '<U50'), ('ID', '<i8'), ('Age', '<f8')])

In [176]:
p7 = np.arange(10,200,11)
p7

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109, 120, 131, 142,
       153, 164, 175, 186, 197])

In [177]:
np.savetxt('test3.csv', p7, delimiter=',')

In [178]:
p8 = np.arange(0,121).reshape(11,11)
p8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [179]:
np.save('test4.npy', p8)

In [180]:
p9 = np.load('test4.npy')
p9

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [181]:
np.save('numpyfile', p8)

In [182]:
p10 = np.load('numpyfile.npy')
p10

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [183]:
p11 = np.arange(0,1000000).reshape(1000,1000)
p11

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [184]:
# Save Numpy array to a compressed file
np.savez_compressed('test6.npz', p11)

In [185]:
# Save Numpy array to a npy file
np.save('test7.npy', p11)

In [186]:
# Compressed file size is much lesser than normal npy file
Image(filename='load_save.PNG')

FileNotFoundError: ignored

In [187]:
# Display values upto 4 decimal place
np.set_printoptions(precision=4)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.6544, 90.7864])

In [188]:
# Display values upto 2 decimal place
np.set_printoptions(precision=2)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.65, 90.79])

In [189]:
# Array Summarization
np.set_printoptions(threshold=3)
np.arange(200)

array([  0,   1,   2, ..., 197, 198, 199])

In [190]:
# Reset Formatter
np.set_printoptions(precision=8,suppress=False, threshold=1000, formatter=None)
a = np.array([12.654398765 , 90.7864098354674])
a

array([12.65439876, 90.78640984])

In [191]:
np.arange(1,1100)

array([   1,    2,    3, ..., 1097, 1098, 1099])

In [192]:
# Display all values
np.set_printoptions(threshold=np.inf)
np.arange(1,1100)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [193]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1+v2
v3 = np.add(v1,v2)
print('V3 =' ,v3)

V3 = [4 6]


In [194]:
a1 = [5 , 6 ,8]
a2 = [4, 7 , 9]
print(np.multiply(a1,a2))

[20 42 72]


In [195]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print(" Dot product - ",dotp)

dotp = np.dot(a1,a2)
print(" Dot product usign np.dot",dotp)

dotp = np.inner(a1,a2)
print(" Dot product usign np.inner", dotp)

dotp = sum(np.multiply(a1,a2))
print(" Dot product usign np.multiply & sum",dotp)

dotp = np.matmul(a1,a2)
print(" Dot product usign np.matmul",dotp)

dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print(" Dot product usign for loop" , dotp)

 Dot product -  32
 Dot product usign np.dot 32
 Dot product usign np.inner 32
 Dot product usign np.multiply & sum 32
 Dot product usign np.matmul 32
 Dot product usign for loop 32


In [196]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [197]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(sum(np.multiply(v3,v3)))
length

9.539392014169456

In [198]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.matmul(v3,v3))
length

9.539392014169456

In [199]:
#First Method
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1 = v1/length_v1
length_v1 , norm_v1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [200]:
#Second Method
v1 = np.array([4,3])
v2 = np.array([-3,4])
lengthV1 = np.sqrt(np.dot(v1,v1)) 
lengthV2  = np.sqrt(np.dot(v2,v2))
ang = np.rad2deg(np.arccos( np.dot(v1,v2) / (lengthV1 * lengthV2)))
print('Angle between Vectors - %s' %ang)

Angle between Vectors - 90.0


In [201]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.inner(v1,v2)

print("\n Inner Product ==>  \n", np.inner(v1,v2))
print("\n Outer Product ==>  \n", np.outer(v1,v2))


 Inner Product ==>  
 32

 Outer Product ==>  
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [202]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("\nVector Cross Product ==>  \n", np.cross(v1,v2))


Vector Cross Product ==>  
 [-3  6 -3]


In [203]:
# Create a 4x4 matrix
A = np.array([[1,2,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [204]:
# Datatype of Matrix
A.dtype

dtype('int64')

In [205]:
B = np.array([[1.5,2.07,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
B

array([[ 1.5 ,  2.07,  3.  ,  4.  ],
       [ 5.  ,  6.  ,  7.  ,  8.  ],
       [10.  , 11.  , 12.  , 13.  ],
       [14.  , 15.  , 16.  , 17.  ]])

In [206]:
# Datatype of Matrix
B.dtype


dtype('float64')

In [207]:
A.shape

(4, 4)

In [208]:
# Generate a 4x4 zero matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [209]:
#Shape of Matrix
z1 = np.zeros((4,4))
z1.shape

(4, 4)

In [210]:
# Generate a 5x5 matrix filled with ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [211]:
# Return 10x10 matrix of random integer numbers between 0 to 500
np.random.randint(0,500, (10,10))

array([[301,  97, 408, 292, 166, 137, 125,  52,  67, 299],
       [129,  79,  68, 196, 484,  61, 146, 307, 270, 412],
       [401,  87,  46,  52, 144, 454, 455,  84,  10, 190],
       [362,  96, 122, 235, 498, 487, 493, 185, 151, 470],
       [469,  26,  76,  66, 232,  54, 145, 193, 185, 473],
       [258,  80,  50, 322,  88,  79, 349,   6, 348,  42],
       [ 22, 377, 244, 368, 404, 409, 383,  97, 110, 438],
       [ 71, 456, 208, 221, 192, 364,  63, 488, 359, 208],
       [422, 301, 359, 103, 372, 163,  25, 223,  75, 456],
       [ 11, 332, 207, 369, 379, 306, 239, 150, 101,  59]])

In [212]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [213]:
arr2.reshape(5,4)

ValueError: ignored

In [214]:
mat1 = np.random.randint(0,1000,100).reshape(10,10)
mat1

array([[834, 358, 490, 634,   1, 546, 549, 441,  35, 810],
       [115, 869, 684, 242, 108, 177, 671,  79,  85, 515],
       [311, 841, 221, 478, 611,  40, 694, 984, 350, 871],
       [982, 757, 145, 245, 759, 580, 401, 402, 444, 851],
       [594, 647, 579, 764, 930, 251, 588, 895, 606, 119],
       [788, 453, 841,  59, 546, 502, 453, 635, 376, 537],
       [718, 988, 330, 587, 289, 905, 939,  20, 722, 158],
       [771, 430, 797, 559, 539, 977, 967,  25, 238, 606],
       [102, 697, 405, 541, 390, 310,  47,  47, 828, 646],
       [971,  97, 437, 684, 738, 679, 380, 928, 983, 590]])

In [216]:
mat1[0,0]

834

In [217]:
mat1[mat1 > 500]

array([834, 634, 546, 549, 810, 869, 684, 671, 515, 841, 611, 694, 984,
       871, 982, 757, 759, 580, 851, 594, 647, 579, 764, 930, 588, 895,
       606, 788, 841, 546, 502, 635, 537, 718, 988, 587, 905, 939, 722,
       771, 797, 559, 539, 977, 967, 606, 697, 541, 828, 646, 971, 684,
       738, 679, 928, 983, 590])

In [218]:
# Identity Matrix : https://en.wikipedia.org/wiki/Identity_matrix

I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [215]:
# Diagonal Matrix : https://en.wikipedia.org/wiki/Diagonal_matrix

D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [219]:
# Traingular Matrices (lower & Upper triangular matrix) : https://en.wikipedia.org/wiki/Triangular_matrix

M = np.random.randn(5,5)
U = np.triu(M)
L = np.tril(M)
print("lower triangular matrix - \n" , M)
print("\n")


print("lower triangular matrix - \n" , L)
print("\n")

print("Upper triangular matrix - \n" , U)

lower triangular matrix - 
 [[-0.3801035  -1.66605918 -2.7369946   1.52256211  0.17800909]
 [-0.62680541 -0.39108897  1.74347695  1.13001805  0.89779631]
 [ 0.33086562 -1.06304889 -0.1253808  -0.94558812  2.02954418]
 [-1.04635839 -1.30648231 -1.632924    0.80212937 -1.66753678]
 [ 0.60885729  0.28647299 -0.2057923   2.49399019 -0.54725989]]


lower triangular matrix - 
 [[-0.3801035   0.          0.          0.          0.        ]
 [-0.62680541 -0.39108897  0.          0.          0.        ]
 [ 0.33086562 -1.06304889 -0.1253808   0.          0.        ]
 [-1.04635839 -1.30648231 -1.632924    0.80212937  0.        ]
 [ 0.60885729  0.28647299 -0.2057923   2.49399019 -0.54725989]]


Upper triangular matrix - 
 [[-0.3801035  -1.66605918 -2.7369946   1.52256211  0.17800909]
 [ 0.         -0.39108897  1.74347695  1.13001805  0.89779631]
 [ 0.          0.         -0.1253808  -0.94558812  2.02954418]
 [ 0.          0.          0.          0.80212937 -1.66753678]
 [ 0.          0.          0

In [220]:
# Generate a 5X5 matrix with a given fill value of 8
np.full((5,5) , 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [221]:
# Generate 5X5 matrix of Random float numbers between 10 to 20
np.random.uniform(10,20, size=(5,5))

array([[13.42029574, 12.55531469, 12.32678496, 17.61116921, 19.43450384],
       [14.77820256, 10.30843665, 15.92119504, 13.36773203, 15.04141144],
       [10.23746007, 13.11636371, 18.57556494, 14.05956796, 15.75889026],
       [16.91157062, 18.6385074 , 18.33513445, 17.68023158, 12.86670296],
       [13.05824431, 18.25903961, 15.70742116, 12.48130321, 10.12546232]])

In [222]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [223]:
# Collapse Matrix into one dimension array
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

In [224]:
# Collapse Matrix into one dimension array
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

In [225]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [226]:
# Fetch first row of matrix
A[0,]

array([1, 2, 3, 4])

In [227]:
# Fetch first column of matrix
A[:,0]

array([ 1,  5, 10, 14])

In [228]:
A[1:3 , 1:3]

array([[ 6,  7],
       [11, 12]])

In [229]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [230]:
# Reverse rows
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [231]:
#Reverse Columns
arr[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [232]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [233]:
# SWAP rows 0 & 1
m1[[0,1]] = m1[[1,0]]
m1


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [234]:
# SWAP rows 2 & 3
m1[[3,2]] = m1[[2,3]]
m1


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [235]:
m2 = np.arange(0,36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [236]:
# Swap columns 0 & 1
m2[:,[0, 1]] = m2[:,[1, 0]]
m2

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

In [237]:
# Swap columns 2 & 3
m2[:,[2, 3]] = m2[:,[3, 2]]
m2

array([[ 1,  0,  3,  2,  4,  5],
       [ 7,  6,  9,  8, 10, 11],
       [13, 12, 15, 14, 16, 17],
       [19, 18, 21, 20, 22, 23],
       [25, 24, 27, 26, 28, 29],
       [31, 30, 33, 32, 34, 35]])

In [238]:
A = np.array([[1,2] , [3,4] ,[5,6]])
B = np.array([[1,1] , [1,1]])
C = np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

In [239]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

C = M+N
print("\n Matrix Addition (M+N)  ==>  \n", C)

# OR

C = np.add(M,N,dtype = np.float64)
print("\n Matrix Addition using np.add  ==>  \n", C)

#********************************************************#



 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Addition (M+N)  ==>  
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add  ==>  
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


In [240]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

C = M-N
print("\n Matrix Subtraction (M-N)  ==>  \n", C)

# OR

C = np.subtract(M,N,dtype = np.float64)
print("\n Matrix Subtraction using np.subtract  ==>  \n", C)

#********************************************************#



 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Subtraction (M-N)  ==>  
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix Subtraction using np.subtract  ==>  
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


In [241]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

C = 10

print("\n Matrix (M)  ==>  \n", M)

print("\nMatrices Scalar Multiplication ==>  \n", C*M)

# OR

print("\nMatrices Scalar Multiplication ==>  \n", np.multiply(C,M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Matrices Scalar Multiplication ==>  
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]

Matrices Scalar Multiplication ==>  
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]


In [242]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nTranspose of M ==>  \n", np.transpose(M))

# OR

print("\nTranspose of M ==>  \n", M.T)



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==>  
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [243]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nDeterminant of M ==>  ", np.linalg.det(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Determinant of M ==>   195.0


In [244]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nRank of M ==> ", np.linalg.matrix_rank(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of M ==>  3


In [245]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nTrace of M ==> ", np.trace(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Trace of M ==>  -2


In [246]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])

print("\n Matrix (M)  ==>  \n", M)

print("\nInverse of M ==> \n", np.linalg.inv(M))



 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [247]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

print("\n Point-Wise Multiplication of M & N  ==> \n", M*N)

# OR

print("\n Point-Wise Multiplication of M & N  ==> \n", np.multiply(M,N))



 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [248]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)

print("\n Matrix Dot Product ==> \n", M@N)

# OR

print("\n Matrix Dot Product using np.matmul ==> \n", np.matmul(M,N))

# OR

print("\n Matrix Dot Product using np.dot ==> \n", np.dot(M,N))



 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Dot Product ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.matmul ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.dot ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]


In [249]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)


print("\n Matrix Division (M/N)   ==> \n", M/N)

# OR

print("\n Matrix Division (M/N)   ==> \n", np.divide(M,N))



 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


In [250]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)


print ("Sum of all elements in a Matrix  ==>")
print (np.sum(N))



 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix  ==>
18


In [251]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))



 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


In [252]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])

print("\n Matrix (N)  ==>  \n", N)

print ("Row-Wise summation  ==>")
print (np.sum(N,axis=1))



 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation  ==>
[3 6 9]


In [253]:
M1 = np.array([[1,2,3] , [4,5,6]]) 
M1


array([[1, 2, 3],
       [4, 5, 6]])

In [254]:
M2 = np.array([[10,10,10],[10,10,10]])
M2


array([[10, 10, 10],
       [10, 10, 10]])

In [255]:
np.kron(M1,M2)


array([[10, 10, 10, 20, 20, 20, 30, 30, 30],
       [10, 10, 10, 20, 20, 20, 30, 30, 30],
       [40, 40, 40, 50, 50, 50, 60, 60, 60],
       [40, 40, 40, 50, 50, 50, 60, 60, 60]])

In [256]:
M1 = np.array([[1,2],[4,5]])
M1


array([[1, 2],
       [4, 5]])

In [257]:
#Matrix to the power 3

M1@M1@M1


array([[ 57,  78],
       [156, 213]])

In [258]:
#Matrix to the power 3

np.linalg.matrix_power(M1,3)


array([[ 57,  78],
       [156, 213]])

In [259]:
# Create Tensor

T1 = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[10,20,30], [40,50,60], [70,80,90]],
  [[100,200,300], [400,500,600], [700,800,900]],
  ])

T1


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [260]:
T2 = np.array([
  [[0,0,0] , [0,0,0] , [0,0,0]],
  [[1,1,1] , [1,1,1] , [1,1,1]],
  [[2,2,2] , [2,2,2] , [2,2,2]]
    
])

T2


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [261]:
A = T1+T2
A


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [262]:
np.add(T1,T2)


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [263]:
S = T1-T2
S


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [264]:
np.subtract(T1,T2)


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [265]:
P = T1*T2
P


array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [266]:
np.multiply(T1,T2)


array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [267]:
D = T1/T2
D


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [268]:
np.divide(T1,T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [269]:
T1


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [271]:
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [272]:
np.tensordot(T1,T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

In [276]:
A = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
B = np.random.random((3,1))
B


array([[0.89556177],
       [0.7552261 ],
       [0.66903193]])

In [ ]:
# Ist Method
X = np.dot(np.linalg.inv(A) , B)
X


In [279]:
# 2nd Method
X = np.matmul(np.linalg.inv(A) , B)
X

LinAlgError: ignored